# Generated by Django 3.2.12 on 2022-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main_category', 'verbose_name_plural': 'Main_categories'},
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
