# Generated by Django 3.2.12 on 2022-07-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
