# Generated by Django 3.2.12 on 2022-07-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='rating',
        ),
    ]
